# Write your MySQL query statement below
WITH CTE AS (SELECT 
*,
CASE 
    WHEN (COUNT( DEPARTMENT_ID) OVER(PARTITION BY EMPLOYEE_ID)>1 
            AND PRIMARY_FLAG='Y' ) 
        OR  (COUNT( DEPARTMENT_ID) OVER(PARTITION BY EMPLOYEE_ID)=1) 
    THEN TRUE 
    ELSE FALSE END AS FLG
FROM
    EMPLOYEE)
SELECT EMPLOYEE_ID,DEPARTMENT_ID FROM CTE WHERE FLG = 1
;

